### ISSUE TITLE
Error in building Docker

### ISSUE THREAD

**Issue by twicy** [Shpota/go-angular#36]
Hi, first of all many thanks to your nice project, but I have a little trouble running your program and it looks like this after I execute:

docker build -t students-app .

<img width="845" alt="Screenshot 2022-06-24 170134" src="https://user-images.githubusercontent.com/47052648/175502338-25219c5a-d03e-4549-ac5f-0dad2b788484.png">

Any hint?

**Comment by Shpota** [comment]
Hi @twicy 

It looks like it cannot pull the the UUID dependency. I am not quite sure why. I would suggest you try building it locally and see if it fails with the same error (maybe something is wrong with Docker networks on your machine). Also try updating [the broken dependency](https://github.com/google/uuid) to the latest version and see if it helps.

I haven't touched this project for three years, I expect the libraries might be removed or something else.

If you manage to fix the error, feel free to create a PR. Otherwise I will take a look at it when I have time.

**Comment by Shpota** [comment]
Most likely network issue on your side. Could it be that you have some security restrictions in your network? It worked fine when I tried building the image.
